default_agent: bank_iq_agent_v1
agents:
  bank-iq-agent:
    name: bank-iq-agent
    entrypoint: bank_iq_agent_v1.py
    platform: linux/amd64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: false
      account: null
      region: null
      ecr_repository: null
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  bank_iq_agent_v1:
    name: bank_iq_agent_v1
    entrypoint: bank_iq_agent_v1.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::164543933824:role/BedrockAgentCoreExecutionRole
      execution_role_auto_create: true
      account: '164543933824'
      region: us-east-1
      ecr_repository: 164543933824.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bank_iq_agent_v1
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bank_iq_agent_v1-8r28UWE5Z8
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:runtime/bank_iq_agent_v1-8r28UWE5Z8
      agent_session_id: 5806b8a6-29b6-447a-abcc-a7973390057a
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: bank_iq_agent_v1_mem-1RUigaA4KT
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:164543933824:memory/bank_iq_agent_v1_mem-1RUigaA4KT
      memory_name: bank_iq_agent_v1_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
