AWSTemplateFormatVersion: '2010-09-09'
Description: 'BankIQ+ Authentication - Cognito User Pool with Hosted UI'

Parameters:
  ProjectName:
    Type: String
    Default: bankiq
    Description: Project name for resource naming
  
  CallbackURL:
    Type: String
    Description: CloudFront URL for OAuth callback
    Default: https://localhost:3000
  
  Environment:
    Type: String
    Default: prod
    Description: Environment name

Resources:
  # ============================================================================
  # COGNITO USER POOL
  # ============================================================================
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-users-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Schema:
        - Name: email
          Required: true
          Mutable: false
          AttributeDataType: String
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 7
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false  # Allow self-signup
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      UserPoolTags:
        Name: !Sub '${ProjectName}-user-pool'
        Environment: !Ref Environment

  # ============================================================================
  # COGNITO USER POOL DOMAIN (for Hosted UI)
  # ============================================================================
  
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ProjectName}-auth-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # ============================================================================
  # COGNITO APP CLIENT
  # ============================================================================
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-web-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false  # Public client (SPA)
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref CallbackURL
        - http://localhost:3000
      LogoutURLs:
        - !Ref CallbackURL
        - http://localhost:3000
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  HostedUIUrl:
    Description: Cognito Hosted UI URL
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-HostedUIUrl'
  
  CognitoDomain:
    Description: Cognito Domain
    Value: !Sub '${ProjectName}-auth-${AWS::AccountId}'
    Export:
      Name: !Sub '${AWS::StackName}-CognitoDomain'
  
  LoginUrl:
    Description: Direct login URL
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=code&redirect_uri=${CallbackURL}'
    Export:
      Name: !Sub '${AWS::StackName}-LoginUrl'
